/**
 * 聲の仮名 · 題庫
 * kanaSequence: 拗音整格（きゃ・りょ…）、長音「ー」、撥音「ん」各一格
 * kanji: 漢字表記（答對飄字優先顯示）；zh: 繁中詞義
 * 硬上限 16 格
 */
window.KANA_QUESTIONS = [

  // —— 示範保留 ——
  { id: "goku", contentType: "character", displayName: "孫悟空", kanaSequence: ["ご", "く", "う"], kanji: "孫悟空", zh: "孫悟空", speakText: "ごくう", rewardMode: "celebrate", tags: ["角色", "入門"] },
  { id: "sakura", contentType: "character", displayName: "さくら", kanaSequence: ["さ", "く", "ら"], kanji: "桜", zh: "小櫻", speakText: "さくら", rewardMode: "celebrate", tags: ["角色", "入門"] },
  { id: "domain", contentType: "skill", displayName: "領域展開", kanaSequence: ["りょ", "う", "い", "き", "て", "ん", "か", "い"], kanji: "領域展開", speakText: "りょういきてんかい", castSpeakText: "りょういきてんかい！", castSubtitle: "領域展開", rewardMode: "cast_skill", tags: ["招式", "拗音"] },

  // —— 角色名 ——
  { id: "naruto", contentType: "character", displayName: "ナルト", kanaSequence: ["ナ", "ル", "ト"], zh: "鳴人", speakText: "ナルト", rewardMode: "celebrate", tags: ["角色", "片仮名"] },
  { id: "luffy", contentType: "character", displayName: "ルフィ", kanaSequence: ["ル", "フィ"], zh: "魯夫", speakText: "ルフィ", rewardMode: "celebrate", tags: ["角色", "拗音"] },
  { id: "ichigo", contentType: "character", displayName: "いちご", kanaSequence: ["い", "ち", "ご"], kanji: "一護", zh: "一護", speakText: "いちご", rewardMode: "celebrate", tags: ["角色"] },
  { id: "tanjiro", contentType: "character", displayName: "たんじろう", kanaSequence: ["た", "ん", "じ", "ろ", "う"], kanji: "炭治郎", zh: "炭治郎", speakText: "たんじろう", rewardMode: "celebrate", tags: ["角色"] },
  { id: "nezuko", contentType: "character", displayName: "ねずこ", kanaSequence: ["ね", "ず", "こ"], kanji: "禰豆子", zh: "禰豆子", speakText: "ねずこ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "vegeta", contentType: "character", displayName: "ベジータ", kanaSequence: ["ベ", "ジ", "ー", "タ"], zh: "貝吉塔", speakText: "ベジータ", rewardMode: "celebrate", tags: ["角色", "長音"] },
  { id: "pikachu", contentType: "character", displayName: "ピカチュウ", kanaSequence: ["ピ", "カ", "チュ", "ウ"], zh: "皮卡丘", speakText: "ピカチュウ", rewardMode: "celebrate", tags: ["角色", "拗音"] },
  { id: "ashitaka", contentType: "character", displayName: "アシタカ", kanaSequence: ["ア", "シ", "タ", "カ"], zh: "阿席達卡", speakText: "アシタカ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "totoro", contentType: "character", displayName: "トトロ", kanaSequence: ["ト", "ト", "ロ"], zh: "龍貓", speakText: "トトロ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "chihiro", contentType: "character", displayName: "ちひろ", kanaSequence: ["ち", "ひ", "ろ"], kanji: "千尋", zh: "千尋", speakText: "ちひろ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "howl", contentType: "character", displayName: "ハウル", kanaSequence: ["ハ", "ウ", "ル"], zh: "霍爾", speakText: "ハウル", rewardMode: "celebrate", tags: ["角色"] },
  { id: "eren", contentType: "character", displayName: "エレン", kanaSequence: ["エ", "レ", "ン"], zh: "艾連", speakText: "エレン", rewardMode: "celebrate", tags: ["角色"] },
  { id: "mikasa", contentType: "character", displayName: "ミカサ", kanaSequence: ["ミ", "カ", "サ"], zh: "米卡莎", speakText: "ミカサ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "levi", contentType: "character", displayName: "リヴァイ", kanaSequence: ["リ", "ヴァ", "イ"], zh: "里維", speakText: "リヴァイ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "saitama", contentType: "character", displayName: "サイタマ", kanaSequence: ["サ", "イ", "タ", "マ"], zh: "埼玉", speakText: "サイタマ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "genos", contentType: "character", displayName: "ジェノス", kanaSequence: ["ジェ", "ノ", "ス"], zh: "傑諾斯", speakText: "ジェノス", rewardMode: "celebrate", tags: ["角色", "拗音"] },
  { id: "midoriya", contentType: "character", displayName: "みどりや", kanaSequence: ["み", "ど", "り", "や"], kanji: "緑谷", zh: "綠谷", speakText: "みどりや", rewardMode: "celebrate", tags: ["角色"] },
  { id: "bakugo", contentType: "character", displayName: "ばくごう", kanaSequence: ["ば", "く", "ご", "う"], kanji: "爆豪", zh: "爆豪", speakText: "ばくごう", rewardMode: "celebrate", tags: ["角色"] },
  { id: "rem", contentType: "character", displayName: "レム", kanaSequence: ["レ", "ム"], zh: "雷姆", speakText: "レム", rewardMode: "celebrate", tags: ["角色", "入門"] },
  { id: "ram", contentType: "character", displayName: "ラム", kanaSequence: ["ラ", "ム"], zh: "拉姆", speakText: "ラム", rewardMode: "celebrate", tags: ["角色", "入門"] },
  { id: "asuna", contentType: "character", displayName: "アスナ", kanaSequence: ["ア", "ス", "ナ"], zh: "亞絲娜", speakText: "アスナ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "kirito", contentType: "character", displayName: "キリト", kanaSequence: ["キ", "リ", "ト"], zh: "桐人", speakText: "キリト", rewardMode: "celebrate", tags: ["角色"] },

  // —— 招式名 ——
  { id: "kamehameha", contentType: "skill", displayName: "かめはめ波", kanaSequence: ["か", "め", "は", "め", "は"], kanji: "かめはめ波", speakText: "かめはめは", castSpeakText: "かめはめはー！", castSubtitle: "かめはめ波", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "rasengan", contentType: "skill", displayName: "螺旋丸", kanaSequence: ["ら", "せ", "ん", "が", "ん"], kanji: "螺旋丸", speakText: "らせんがん", castSpeakText: "らせんがん！", castSubtitle: "螺旋丸", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "chidori", contentType: "skill", displayName: "千鳥", kanaSequence: ["ち", "ど", "り"], kanji: "千鳥", speakText: "ちどり", castSpeakText: "ちどり！", castSubtitle: "千鳥", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "bankai", contentType: "skill", displayName: "卍解", kanaSequence: ["ば", "ん", "か", "い"], kanji: "卍解", speakText: "ばんかい", castSpeakText: "ばんかい！", castSubtitle: "卍解", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "getsuga", contentType: "skill", displayName: "月牙天衝", kanaSequence: ["げ", "つ", "が", "て", "ん", "しょ", "う"], kanji: "月牙天衝", speakText: "げつがてんしょう", castSpeakText: "げつがてんしょう！", castSubtitle: "月牙天衝", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "finalflash", contentType: "skill", displayName: "ファイナルフラッシュ", kanaSequence: ["ファ", "イ", "ナ", "ル", "フ", "ラ", "ッ", "シュ"], speakText: "ファイナルフラッシュ", castSpeakText: "ファイナルフラッシュ！", castSubtitle: "ファイナルフラッシュ", rewardMode: "cast_skill", tags: ["招式", "片仮名"] },
  { id: "spiritbomb", contentType: "skill", displayName: "元気玉", kanaSequence: ["げ", "ん", "き", "だ", "ま"], kanji: "元気玉", speakText: "げんきだま", castSpeakText: "げんきだま！", castSubtitle: "元気玉", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "sharingan", contentType: "skill", displayName: "写輪眼", kanaSequence: ["しゃ", "り", "ん", "が", "ん"], kanji: "写輪眼", speakText: "しゃりんがん", castSpeakText: "しゃりんがん！", castSubtitle: "写輪眼", rewardMode: "cast_skill", tags: ["招式", "拗音"] },
  { id: "susanoo", contentType: "skill", displayName: "須佐能乎", kanaSequence: ["す", "さ", "の", "お"], kanji: "須佐能乎", speakText: "すさのお", castSpeakText: "すさのお！", castSubtitle: "須佐能乎", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "amaterasu", contentType: "skill", displayName: "天照", kanaSequence: ["あ", "ま", "て", "ら", "す"], kanji: "天照", speakText: "あまてらす", castSpeakText: "あまてらす！", castSubtitle: "天照", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "hijutsu", contentType: "skill", displayName: "影分身の術", kanaSequence: ["か", "げ", "ぶ", "ん", "し", "ん", "の", "じゅ", "つ"], kanji: "影分身の術", speakText: "かげぶんしんのじゅつ", castSpeakText: "かげぶんしんのじゅつ！", castSubtitle: "影分身の術", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "omoiyari", contentType: "skill", displayName: "水の呼吸", kanaSequence: ["み", "ず", "の", "こ", "きゅ", "う"], kanji: "水の呼吸", speakText: "みずのこきゅう", castSpeakText: "みずのこきゅう！", castSubtitle: "水の呼吸", rewardMode: "cast_skill", tags: ["招式", "拗音"] },
  { id: "hinokami", contentType: "skill", displayName: "ヒノカミ神楽", kanaSequence: ["ヒ", "ノ", "カ", "ミ", "か", "ぐ", "ら"], kanji: "ヒノカミ神楽", speakText: "ヒノカミかぐら", castSpeakText: "ヒノカミかぐら！", castSubtitle: "ヒノカミ神楽", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "oneforall", contentType: "skill", displayName: "ワン・フォー・オール", kanaSequence: ["ワ", "ン", "フォ", "ー", "オ", "ー", "ル"], speakText: "ワンフォーオール", castSpeakText: "ワンフォーオール！", castSubtitle: "ワン・フォー・オール", rewardMode: "cast_skill", tags: ["招式", "片仮名"] },
  { id: "detroit", contentType: "skill", displayName: "デトロイトスマッシュ", kanaSequence: ["デ", "ト", "ロ", "イ", "ト", "ス", "マ", "ッ", "シュ"], speakText: "デトロイトスマッシュ", castSpeakText: "デトロイトスマッシュ！", castSubtitle: "デトロイトスマッシュ", rewardMode: "cast_skill", tags: ["招式", "長詞"] },
  { id: "expulsion", contentType: "skill", displayName: "爆破", kanaSequence: ["ば", "く", "は"], kanji: "爆破", speakText: "ばくは", castSpeakText: "ばくは！", castSubtitle: "爆破", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "seriouspunch", contentType: "skill", displayName: "マジ殴り", kanaSequence: ["マ", "ジ", "な", "ぐ", "り"], kanji: "マジ殴り", speakText: "マジなぐり", castSpeakText: "マジなぐり！", castSubtitle: "マジ殴り", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "gumgum", contentType: "skill", displayName: "ゴムゴムのピストル", kanaSequence: ["ゴ", "ム", "ゴ", "ム", "の", "ピ", "ス", "ト", "ル"], speakText: "ゴムゴムのピストル", castSpeakText: "ゴムゴムのピストル！", castSubtitle: "ゴムゴムのピストル", rewardMode: "cast_skill", tags: ["招式", "長詞"] },
  { id: "gearsecond", contentType: "skill", displayName: "ギア・セカンド", kanaSequence: ["ギ", "ア", "セ", "カ", "ン", "ド"], speakText: "ギアセカンド", castSpeakText: "ギアセカンド！", castSubtitle: "ギア・セカンド", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "blackflash", contentType: "skill", displayName: "黒閃", kanaSequence: ["こ", "く", "せ", "ん"], kanji: "黒閃", speakText: "こくせん", castSpeakText: "こくせん！", castSubtitle: "黒閃", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "hollowpurple", contentType: "skill", displayName: "虚式茈", kanaSequence: ["きょ", "し", "き", "む", "ら", "さ", "き"], kanji: "虚式茈", speakText: "きょしきむらさき", castSpeakText: "きょしきむらさき！", castSubtitle: "虚式茈", rewardMode: "cast_skill", tags: ["招式", "拗音"] },
  { id: "infinitevoid", contentType: "skill", displayName: "無量空処", kanaSequence: ["む", "りょ", "う", "く", "う", "しょ"], kanji: "無量空処", speakText: "むりょうくうしょ", castSpeakText: "むりょうくうしょ！", castSubtitle: "無量空処", rewardMode: "cast_skill", tags: ["招式", "拗音"] },
  { id: "malevolent", contentType: "skill", displayName: "伏魔御厨子", kanaSequence: ["ふ", "く", "ま", "ご", "ず", "し"], kanji: "伏魔御厨子", speakText: "ふくまごずし", castSpeakText: "ふくまごずし！", castSubtitle: "伏魔御厨子", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "shikai", contentType: "skill", displayName: "始解", kanaSequence: ["し", "か", "い"], kanji: "始解", speakText: "しかい", castSpeakText: "しかい！", castSubtitle: "始解", rewardMode: "cast_skill", tags: ["招式", "入門"] },
  { id: "hado31", contentType: "skill", displayName: "赤火砲", kanaSequence: ["しゃ", "っ", "か", "ほ", "う"], kanji: "赤火砲", speakText: "しゃっかほう", castSpeakText: "しゃっかほう！", castSubtitle: "赤火砲", rewardMode: "cast_skill", tags: ["招式", "拗音"] },

  // —— 自創／中二招式 ——
  { id: "custom_star", contentType: "custom_skill", displayName: "星屑螺旋", kanaSequence: ["ほ", "し", "く", "ず", "ら", "せ", "ん"], kanji: "星屑螺旋", speakText: "ほしくずらせん", castSpeakText: "ほしくずらせん！", castSubtitle: "星屑螺旋", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_thunder", contentType: "custom_skill", displayName: "蒼天雷鳴斬", kanaSequence: ["そ", "う", "て", "ん", "ら", "い", "め", "い", "ざ", "ん"], kanji: "蒼天雷鳴斬", speakText: "そうてんらいめいざん", castSpeakText: "そうてんらいめいざん！", castSubtitle: "蒼天雷鳴斬", rewardMode: "cast_skill", tags: ["自創", "長詞"] },
  { id: "custom_moon", contentType: "custom_skill", displayName: "月影一閃", kanaSequence: ["つ", "き", "か", "げ", "い", "っ", "せ", "ん"], kanji: "月影一閃", speakText: "つきかげいっせん", castSpeakText: "つきかげいっせん！", castSubtitle: "月影一閃", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_flame", contentType: "custom_skill", displayName: "紅蓮業火", kanaSequence: ["ぐ", "れ", "ん", "ご", "う", "か"], kanji: "紅蓮業火", speakText: "ぐれんごうか", castSpeakText: "ぐれんごうか！", castSubtitle: "紅蓮業火", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_ice", contentType: "custom_skill", displayName: "絶対零度", kanaSequence: ["ぜ", "っ", "た", "い", "れ", "い", "ど"], kanji: "絶対零度", speakText: "ぜったいれいど", castSpeakText: "ぜったいれいど！", castSubtitle: "絶対零度", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_wind", contentType: "custom_skill", displayName: "疾風迅雷", kanaSequence: ["し", "っ", "ぷ", "う", "じ", "ん", "ら", "い"], kanji: "疾風迅雷", speakText: "しっぷうじんらい", castSpeakText: "しっぷうじんらい！", castSubtitle: "疾風迅雷", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_void", contentType: "custom_skill", displayName: "虚空断裂", kanaSequence: ["こ", "く", "う", "だ", "ん", "れ", "つ"], kanji: "虚空断裂", speakText: "こくうだんれつ", castSpeakText: "こくうだんれつ！", castSubtitle: "虚空断裂", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_dragon", contentType: "custom_skill", displayName: "竜神の咆哮", kanaSequence: ["りゅ", "う", "じ", "ん", "の", "ほ", "う", "こ", "う"], kanji: "竜神の咆哮", speakText: "りゅうじんのほうこう", castSpeakText: "りゅうじんのほうこう！", castSubtitle: "竜神の咆哮", rewardMode: "cast_skill", tags: ["自創", "拗音"] },
  { id: "custom_light", contentType: "custom_skill", displayName: "聖光の審判", kanaSequence: ["せ", "い", "こ", "う", "の", "し", "ん", "ぱ", "ん"], kanji: "聖光の審判", speakText: "せいこうのしんぱん", castSpeakText: "せいこうのしんぱん！", castSubtitle: "聖光の審判", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_shadow", contentType: "custom_skill", displayName: "闇影縛鎖", kanaSequence: ["あ", "ん", "え", "い", "ば", "く", "さ"], kanji: "闇影縛鎖", speakText: "あんえいばくさ", castSpeakText: "あんえいばくさ！", castSubtitle: "闇影縛鎖", rewardMode: "cast_skill", tags: ["自創"] },

  // —— 日常・N5 詞彙 ——
  { id: "arigatou", contentType: "vocab", displayName: "ありがとう", kanaSequence: ["あ", "り", "が", "と", "う"], zh: "謝謝", speakText: "ありがとう", rewardMode: "celebrate", tags: ["日常", "入門"] },
  { id: "ohayou", contentType: "vocab", displayName: "おはよう", kanaSequence: ["お", "は", "よ", "う"], zh: "早安", speakText: "おはよう", rewardMode: "celebrate", tags: ["日常", "入門"] },
  { id: "konnichiwa", contentType: "vocab", displayName: "こんにちは", kanaSequence: ["こ", "ん", "に", "ち", "は"], zh: "你好", speakText: "こんにちは", rewardMode: "celebrate", tags: ["日常", "入門"] },
  { id: "konbanwa", contentType: "vocab", displayName: "こんばんは", kanaSequence: ["こ", "ん", "ば", "ん", "は"], zh: "晚安", speakText: "こんばんは", rewardMode: "celebrate", tags: ["日常"] },
  { id: "sayounara", contentType: "vocab", displayName: "さようなら", kanaSequence: ["さ", "よ", "う", "な", "ら"], zh: "再見", speakText: "さようなら", rewardMode: "celebrate", tags: ["日常"] },
  { id: "sumimasen", contentType: "vocab", displayName: "すみません", kanaSequence: ["す", "み", "ま", "せ", "ん"], zh: "對不起／打擾了", speakText: "すみません", rewardMode: "celebrate", tags: ["日常"] },
  { id: "gomen", contentType: "vocab", displayName: "ごめん", kanaSequence: ["ご", "め", "ん"], zh: "抱歉", speakText: "ごめん", rewardMode: "celebrate", tags: ["日常", "入門"] },
  { id: "onegaishimasu", contentType: "vocab", displayName: "お願いします", kanaSequence: ["お", "ね", "が", "い", "し", "ま", "す"], kanji: "お願いします", zh: "拜託了", speakText: "おねがいします", rewardMode: "celebrate", tags: ["日常"] },
  { id: "douzo", contentType: "vocab", displayName: "どうぞ", kanaSequence: ["ど", "う", "ぞ"], zh: "請／不客氣", speakText: "どうぞ", rewardMode: "celebrate", tags: ["日常", "入門"] },
  { id: "hai", contentType: "vocab", displayName: "はい", kanaSequence: ["は", "い"], zh: "是", speakText: "はい", rewardMode: "celebrate", tags: ["日常", "入門"] },
  { id: "iie", contentType: "vocab", displayName: "いいえ", kanaSequence: ["い", "い", "え"], zh: "不是", speakText: "いいえ", rewardMode: "celebrate", tags: ["日常", "入門"] },
  { id: "wakarimasu", contentType: "vocab", displayName: "わかります", kanaSequence: ["わ", "か", "り", "ま", "す"], kanji: "分かります", zh: "明白", speakText: "わかります", rewardMode: "celebrate", tags: ["日常"] },
  { id: "tabemasu", contentType: "vocab", displayName: "たべます", kanaSequence: ["た", "べ", "ま", "す"], kanji: "食べます", zh: "吃", speakText: "たべます", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "nomimasu", contentType: "vocab", displayName: "のみます", kanaSequence: ["の", "み", "ま", "す"], kanji: "飲みます", zh: "喝", speakText: "のみます", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "ikimasu", contentType: "vocab", displayName: "いきます", kanaSequence: ["い", "き", "ま", "す"], kanji: "行きます", zh: "去", speakText: "いきます", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "kimasu", contentType: "vocab", displayName: "きます", kanaSequence: ["き", "ま", "す"], kanji: "来ます", zh: "來", speakText: "きます", rewardMode: "celebrate", tags: ["動詞", "入門"] },
  { id: "mimasu", contentType: "vocab", displayName: "みます", kanaSequence: ["み", "ま", "す"], kanji: "見ます", zh: "看", speakText: "みます", rewardMode: "celebrate", tags: ["動詞", "入門"] },
  { id: "kikimasu", contentType: "vocab", displayName: "ききます", kanaSequence: ["き", "き", "ま", "す"], kanji: "聞きます", zh: "聽", speakText: "ききます", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "hanashimasu", contentType: "vocab", displayName: "はなします", kanaSequence: ["は", "な", "し", "ま", "す"], kanji: "話します", zh: "說", speakText: "はなします", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "yomimasu", contentType: "vocab", displayName: "よみます", kanaSequence: ["よ", "み", "ま", "す"], kanji: "読みます", zh: "讀", speakText: "よみます", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "kakimasu", contentType: "vocab", displayName: "かきます", kanaSequence: ["か", "き", "ま", "す"], kanji: "書きます", zh: "寫", speakText: "かきます", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "benkyou", contentType: "vocab", displayName: "べんきょう", kanaSequence: ["べ", "ん", "きょ", "う"], kanji: "勉強", zh: "學習", speakText: "べんきょう", rewardMode: "celebrate", tags: ["名詞", "拗音"] },
  { id: "gakkou", contentType: "vocab", displayName: "がっこう", kanaSequence: ["が", "っ", "こ", "う"], kanji: "学校", zh: "學校", speakText: "がっこう", rewardMode: "celebrate", tags: ["名詞", "促音"] },
  { id: "sensei", contentType: "vocab", displayName: "せんせい", kanaSequence: ["せ", "ん", "せ", "い"], kanji: "先生", zh: "老師", speakText: "せんせい", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "tomodachi", contentType: "vocab", displayName: "ともだち", kanaSequence: ["と", "も", "だ", "ち"], kanji: "友達", zh: "朋友", speakText: "ともだち", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "kazoku", contentType: "vocab", displayName: "かぞく", kanaSequence: ["か", "ぞ", "く"], kanji: "家族", zh: "家人", speakText: "かぞく", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "nihongo", contentType: "vocab", displayName: "にほんご", kanaSequence: ["に", "ほ", "ん", "ご"], kanji: "日本語", zh: "日語", speakText: "にほんご", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "eigo", contentType: "vocab", displayName: "えいご", kanaSequence: ["え", "い", "ご"], kanji: "英語", zh: "英語", speakText: "えいご", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "mizu", contentType: "vocab", displayName: "みず", kanaSequence: ["み", "ず"], kanji: "水", zh: "水", speakText: "みず", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "gohan", contentType: "vocab", displayName: "ごはん", kanaSequence: ["ご", "は", "ん"], kanji: "ご飯", zh: "飯", speakText: "ごはん", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "pan", contentType: "vocab", displayName: "パン", kanaSequence: ["パ", "ン"], zh: "麵包", speakText: "パン", rewardMode: "celebrate", tags: ["名詞", "片仮名", "入門"] },
  { id: "ramen", contentType: "vocab", displayName: "ラーメン", kanaSequence: ["ラ", "ー", "メ", "ン"], zh: "拉麵", speakText: "ラーメン", rewardMode: "celebrate", tags: ["名詞", "片仮名", "長音"] },
  { id: "sushi", contentType: "vocab", displayName: "すし", kanaSequence: ["す", "し"], kanji: "寿司", zh: "壽司", speakText: "すし", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "tempura", contentType: "vocab", displayName: "てんぷら", kanaSequence: ["て", "ん", "ぷ", "ら"], kanji: "天ぷら", zh: "天婦羅", speakText: "てんぷら", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "ocha", contentType: "vocab", displayName: "おちゃ", kanaSequence: ["お", "ちゃ"], kanji: "お茶", zh: "茶", speakText: "おちゃ", rewardMode: "celebrate", tags: ["名詞", "拗音", "入門"] },
  { id: "koohii", contentType: "vocab", displayName: "コーヒー", kanaSequence: ["コ", "ー", "ヒ", "ー"], zh: "咖啡", speakText: "コーヒー", rewardMode: "celebrate", tags: ["名詞", "片仮名", "長音"] },
  { id: "denwa", contentType: "vocab", displayName: "でんわ", kanaSequence: ["で", "ん", "わ"], kanji: "電話", zh: "電話", speakText: "でんわ", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "terebi", contentType: "vocab", displayName: "テレビ", kanaSequence: ["テ", "レ", "ビ"], zh: "電視", speakText: "テレビ", rewardMode: "celebrate", tags: ["名詞", "片仮名"] },
  { id: "pasokon", contentType: "vocab", displayName: "パソコン", kanaSequence: ["パ", "ソ", "コ", "ン"], zh: "電腦", speakText: "パソコン", rewardMode: "celebrate", tags: ["名詞", "片仮名"] },
  { id: "keitai", contentType: "vocab", displayName: "けいたい", kanaSequence: ["け", "い", "た", "い"], kanji: "携帯", zh: "手機", speakText: "けいたい", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "densha", contentType: "vocab", displayName: "でんしゃ", kanaSequence: ["で", "ん", "しゃ"], kanji: "電車", zh: "電車", speakText: "でんしゃ", rewardMode: "celebrate", tags: ["名詞", "拗音"] },
  { id: "basu", contentType: "vocab", displayName: "バス", kanaSequence: ["バ", "ス"], zh: "公車", speakText: "バス", rewardMode: "celebrate", tags: ["名詞", "片仮名", "入門"] },
  { id: "takushii", contentType: "vocab", displayName: "タクシー", kanaSequence: ["タ", "ク", "シ", "ー"], zh: "計程車", speakText: "タクシー", rewardMode: "celebrate", tags: ["名詞", "片仮名", "長音"] },
  { id: "hikouki", contentType: "vocab", displayName: "ひこうき", kanaSequence: ["ひ", "こ", "う", "き"], kanji: "飛行機", zh: "飛機", speakText: "ひこうき", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "jikan", contentType: "vocab", displayName: "じかん", kanaSequence: ["じ", "か", "ん"], kanji: "時間", zh: "時間", speakText: "じかん", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "kyou", contentType: "vocab", displayName: "きょう", kanaSequence: ["きょ", "う"], kanji: "今日", zh: "今天", speakText: "きょう", rewardMode: "celebrate", tags: ["名詞", "拗音", "入門"] },
  { id: "ashita", contentType: "vocab", displayName: "あした", kanaSequence: ["あ", "し", "た"], kanji: "明日", zh: "明天", speakText: "あした", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "kinou", contentType: "vocab", displayName: "きのう", kanaSequence: ["き", "の", "う"], kanji: "昨日", zh: "昨天", speakText: "きのう", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "ima", contentType: "vocab", displayName: "いま", kanaSequence: ["い", "ま"], kanji: "今", zh: "現在", speakText: "いま", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "asa", contentType: "vocab", displayName: "あさ", kanaSequence: ["あ", "さ"], kanji: "朝", zh: "早上", speakText: "あさ", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "hiru", contentType: "vocab", displayName: "ひる", kanaSequence: ["ひ", "る"], kanji: "昼", zh: "中午", speakText: "ひる", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "yoru", contentType: "vocab", displayName: "よる", kanaSequence: ["よ", "る"], kanji: "夜", zh: "晚上", speakText: "よる", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "ookii", contentType: "vocab", displayName: "おおきい", kanaSequence: ["お", "お", "き", "い"], kanji: "大きい", zh: "大的", speakText: "おおきい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "chiisai", contentType: "vocab", displayName: "ちいさい", kanaSequence: ["ち", "い", "さ", "い"], kanji: "小さい", zh: "小的", speakText: "ちいさい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "atarashii", contentType: "vocab", displayName: "あたらしい", kanaSequence: ["あ", "た", "ら", "し", "い"], kanji: "新しい", zh: "新的", speakText: "あたらしい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "furui", contentType: "vocab", displayName: "ふるい", kanaSequence: ["ふ", "る", "い"], kanji: "古い", zh: "舊的", speakText: "ふるい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "takai", contentType: "vocab", displayName: "たかい", kanaSequence: ["た", "か", "い"], kanji: "高い", zh: "高／貴", speakText: "たかい", rewardMode: "celebrate", tags: ["形容詞", "入門"] },
  { id: "yasui", contentType: "vocab", displayName: "やすい", kanaSequence: ["や", "す", "い"], kanji: "安い", zh: "便宜", speakText: "やすい", rewardMode: "celebrate", tags: ["形容詞", "入門"] },
  { id: "oishii", contentType: "vocab", displayName: "おいしい", kanaSequence: ["お", "い", "し", "い"], kanji: "美味しい", zh: "好吃", speakText: "おいしい", rewardMode: "celebrate", tags: ["形容詞", "入門"] },
  { id: "tanoshii", contentType: "vocab", displayName: "たのしい", kanaSequence: ["た", "の", "し", "い"], kanji: "楽しい", zh: "開心", speakText: "たのしい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "muzukashii", contentType: "vocab", displayName: "むずかしい", kanaSequence: ["む", "ず", "か", "し", "い"], kanji: "難しい", zh: "難", speakText: "むずかしい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "yasashii", contentType: "vocab", displayName: "やさしい", kanaSequence: ["や", "さ", "し", "い"], kanji: "優しい", zh: "溫柔／簡單", speakText: "やさしい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "kawaii", contentType: "vocab", displayName: "かわいい", kanaSequence: ["か", "わ", "い", "い"], kanji: "可愛い", zh: "可愛", speakText: "かわいい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "sugoi", contentType: "vocab", displayName: "すごい", kanaSequence: ["す", "ご", "い"], kanji: "凄い", zh: "厲害", speakText: "すごい", rewardMode: "celebrate", tags: ["形容詞", "入門"] },
  { id: "daijoubu", contentType: "vocab", displayName: "だいじょうぶ", kanaSequence: ["だ", "い", "じょ", "う", "ぶ"], kanji: "大丈夫", zh: "沒問題", speakText: "だいじょうぶ", rewardMode: "celebrate", tags: ["日常", "拗音"] },
  { id: "genki", contentType: "vocab", displayName: "げんき", kanaSequence: ["げ", "ん", "き"], kanji: "元気", zh: "有精神", speakText: "げんき", rewardMode: "celebrate", tags: ["日常", "入門"] },
  { id: "suki", contentType: "vocab", displayName: "すき", kanaSequence: ["す", "き"], kanji: "好き", zh: "喜歡", speakText: "すき", rewardMode: "celebrate", tags: ["日常", "入門"] },
  { id: "kirai", contentType: "vocab", displayName: "きらい", kanaSequence: ["き", "ら", "い"], kanji: "嫌い", zh: "討厭", speakText: "きらい", rewardMode: "celebrate", tags: ["日常"] },
  { id: "tsukareta", contentType: "vocab", displayName: "つかれた", kanaSequence: ["つ", "か", "れ", "た"], kanji: "疲れた", zh: "累了", speakText: "つかれた", rewardMode: "celebrate", tags: ["日常"] },
  { id: "nemui", contentType: "vocab", displayName: "ねむい", kanaSequence: ["ね", "む", "い"], kanji: "眠い", zh: "想睡", speakText: "ねむい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "samui", contentType: "vocab", displayName: "さむい", kanaSequence: ["さ", "む", "い"], kanji: "寒い", zh: "冷", speakText: "さむい", rewardMode: "celebrate", tags: ["形容詞", "入門"] },
  { id: "atsui", contentType: "vocab", displayName: "あつい", kanaSequence: ["あ", "つ", "い"], kanji: "暑い", zh: "熱", speakText: "あつい", rewardMode: "celebrate", tags: ["形容詞", "入門"] },
  { id: "ame", contentType: "vocab", displayName: "あめ", kanaSequence: ["あ", "め"], kanji: "雨", zh: "雨", speakText: "あめ", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "yuki", contentType: "vocab", displayName: "ゆき", kanaSequence: ["ゆ", "き"], kanji: "雪", zh: "雪", speakText: "ゆき", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "kaze", contentType: "vocab", displayName: "かぜ", kanaSequence: ["か", "ぜ"], kanji: "風", zh: "風", speakText: "かぜ", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "haru", contentType: "vocab", displayName: "はる", kanaSequence: ["は", "る"], kanji: "春", zh: "春", speakText: "はる", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "natsu", contentType: "vocab", displayName: "なつ", kanaSequence: ["な", "つ"], kanji: "夏", zh: "夏", speakText: "なつ", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "aki", contentType: "vocab", displayName: "あき", kanaSequence: ["あ", "き"], kanji: "秋", zh: "秋", speakText: "あき", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "fuyu", contentType: "vocab", displayName: "ふゆ", kanaSequence: ["ふ", "ゆ"], kanji: "冬", zh: "冬", speakText: "ふゆ", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "yama", contentType: "vocab", displayName: "やま", kanaSequence: ["や", "ま"], kanji: "山", zh: "山", speakText: "やま", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "kawa", contentType: "vocab", displayName: "かわ", kanaSequence: ["か", "わ"], kanji: "川", zh: "川", speakText: "かわ", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "umi", contentType: "vocab", displayName: "うみ", kanaSequence: ["う", "み"], kanji: "海", zh: "海", speakText: "うみ", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "sora", contentType: "vocab", displayName: "そら", kanaSequence: ["そ", "ら"], kanji: "空", zh: "天空", speakText: "そら", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "hana", contentType: "vocab", displayName: "はな", kanaSequence: ["は", "な"], kanji: "花", zh: "花", speakText: "はな", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "ki", contentType: "vocab", displayName: "き", kanaSequence: ["き"], kanji: "木", zh: "樹", speakText: "き", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "neko", contentType: "vocab", displayName: "ねこ", kanaSequence: ["ね", "こ"], kanji: "猫", zh: "貓", speakText: "ねこ", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "inu", contentType: "vocab", displayName: "いぬ", kanaSequence: ["い", "ぬ"], kanji: "犬", zh: "狗", speakText: "いぬ", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "tori", contentType: "vocab", displayName: "とり", kanaSequence: ["と", "り"], kanji: "鳥", zh: "鳥", speakText: "とり", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "sakana", contentType: "vocab", displayName: "さかな", kanaSequence: ["さ", "か", "な"], kanji: "魚", zh: "魚", speakText: "さかな", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "ringo", contentType: "vocab", displayName: "りんご", kanaSequence: ["り", "ん", "ご"], zh: "蘋果", speakText: "りんご", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "mikan", contentType: "vocab", displayName: "みかん", kanaSequence: ["み", "か", "ん"], zh: "橘子", speakText: "みかん", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "banana", contentType: "vocab", displayName: "バナナ", kanaSequence: ["バ", "ナ", "ナ"], zh: "香蕉", speakText: "バナナ", rewardMode: "celebrate", tags: ["名詞", "片仮名", "入門"] },
  { id: "aisukuriimu", contentType: "vocab", displayName: "アイスクリーム", kanaSequence: ["ア", "イ", "ス", "ク", "リ", "ー", "ム"], zh: "冰淇淋", speakText: "アイスクリーム", rewardMode: "celebrate", tags: ["名詞", "片仮名", "長音"] },
  { id: "chokoreeto", contentType: "vocab", displayName: "チョコレート", kanaSequence: ["チョ", "コ", "レ", "ー", "ト"], zh: "巧克力", speakText: "チョコレート", rewardMode: "celebrate", tags: ["名詞", "片仮名", "拗音"] },
  { id: "keeki", contentType: "vocab", displayName: "ケーキ", kanaSequence: ["ケ", "ー", "キ"], zh: "蛋糕", speakText: "ケーキ", rewardMode: "celebrate", tags: ["名詞", "片仮名", "長音"] },
  { id: "pizza", contentType: "vocab", displayName: "ピザ", kanaSequence: ["ピ", "ザ"], zh: "披薩", speakText: "ピザ", rewardMode: "celebrate", tags: ["名詞", "片仮名", "入門"] },
  { id: "hanbaagaa", contentType: "vocab", displayName: "ハンバーガー", kanaSequence: ["ハ", "ン", "バ", "ー", "ガ", "ー"], zh: "漢堡", speakText: "ハンバーガー", rewardMode: "celebrate", tags: ["名詞", "片仮名"] },
  { id: "sandoicchi", contentType: "vocab", displayName: "サンドイッチ", kanaSequence: ["サ", "ン", "ド", "イ", "ッ", "チ"], zh: "三明治", speakText: "サンドイッチ", rewardMode: "celebrate", tags: ["名詞", "片仮名"] },
  { id: "jutsu", contentType: "vocab", displayName: "じゅつ", kanaSequence: ["じゅ", "つ"], kanji: "術", zh: "術", speakText: "じゅつ", rewardMode: "celebrate", tags: ["名詞", "拗音", "入門"] },
  { id: "mahou", contentType: "vocab", displayName: "まほう", kanaSequence: ["ま", "ほ", "う"], kanji: "魔法", zh: "魔法", speakText: "まほう", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "ken", contentType: "vocab", displayName: "けん", kanaSequence: ["け", "ん"], kanji: "剣", zh: "劍", speakText: "けん", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "tate", contentType: "vocab", displayName: "たて", kanaSequence: ["た", "て"], kanji: "盾", zh: "盾", speakText: "たて", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "yoroi", contentType: "vocab", displayName: "よろい", kanaSequence: ["よ", "ろ", "い"], kanji: "鎧", zh: "鎧甲", speakText: "よろい", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "yumi", contentType: "vocab", displayName: "ゆみ", kanaSequence: ["ゆ", "み"], kanji: "弓", zh: "弓", speakText: "ゆみ", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "ya", contentType: "vocab", displayName: "や", kanaSequence: ["や"], kanji: "矢", zh: "箭", speakText: "や", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "tatakau", contentType: "vocab", displayName: "たたかう", kanaSequence: ["た", "た", "か", "う"], kanji: "戦う", zh: "戰鬥", speakText: "たたかう", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "mamoru", contentType: "vocab", displayName: "まもる", kanaSequence: ["ま", "も", "る"], kanji: "守る", zh: "守護", speakText: "まもる", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "nigeru", contentType: "vocab", displayName: "にげる", kanaSequence: ["に", "げ", "る"], kanji: "逃げる", zh: "逃跑", speakText: "にげる", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "katsu", contentType: "vocab", displayName: "かつ", kanaSequence: ["か", "つ"], kanji: "勝つ", zh: "贏", speakText: "かつ", rewardMode: "celebrate", tags: ["動詞", "入門"] },
  { id: "makeru", contentType: "vocab", displayName: "まける", kanaSequence: ["ま", "け", "る"], kanji: "負ける", zh: "輸", speakText: "まける", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "yuuki", contentType: "vocab", displayName: "ゆうき", kanaSequence: ["ゆ", "う", "き"], kanji: "勇気", zh: "勇氣", speakText: "ゆうき", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "kibou", contentType: "vocab", displayName: "きぼう", kanaSequence: ["き", "ぼ", "う"], kanji: "希望", zh: "希望", speakText: "きぼう", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "yume", contentType: "vocab", displayName: "ゆめ", kanaSequence: ["ゆ", "め"], kanji: "夢", zh: "夢", speakText: "ゆめ", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "ai", contentType: "vocab", displayName: "あい", kanaSequence: ["あ", "い"], kanji: "愛", zh: "愛", speakText: "あい", rewardMode: "celebrate", tags: ["名詞", "入門"] },
  { id: "heiwa", contentType: "vocab", displayName: "へいわ", kanaSequence: ["へ", "い", "わ"], kanji: "平和", zh: "和平", speakText: "へいわ", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "sensou", contentType: "vocab", displayName: "せんそう", kanaSequence: ["せ", "ん", "そ", "う"], kanji: "戦争", zh: "戰爭", speakText: "せんそう", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "shouri", contentType: "vocab", displayName: "しょうり", kanaSequence: ["しょ", "う", "り"], kanji: "勝利", zh: "勝利", speakText: "しょうり", rewardMode: "celebrate", tags: ["名詞", "拗音"] },
  { id: "haiboku", contentType: "vocab", displayName: "はいぼく", kanaSequence: ["は", "い", "ぼ", "く"], kanji: "敗北", zh: "敗北", speakText: "はいぼく", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "chikara", contentType: "vocab", displayName: "ちから", kanaSequence: ["ち", "か", "ら"], kanji: "力", zh: "力量", speakText: "ちから", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "inochi", contentType: "vocab", displayName: "いのち", kanaSequence: ["い", "の", "ち"], kanji: "命", zh: "生命", speakText: "いのち", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "kokoro", contentType: "vocab", displayName: "こころ", kanaSequence: ["こ", "こ", "ろ"], kanji: "心", zh: "心", speakText: "こころ", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "tamashii", contentType: "vocab", displayName: "たましい", kanaSequence: ["た", "ま", "し", "い"], kanji: "魂", zh: "靈魂", speakText: "たましい", rewardMode: "celebrate", tags: ["名詞"] },
];
