/**
 * 聲の仮名 · 題庫
 * kanaSequence: 拗音整格（きゃ・りょ…）、長音「ー」、撥音「ん」各一格
 * 硬上限 16 格
 */
window.KANA_QUESTIONS = [
  // —— 示範保留 ——
  { id: "goku", contentType: "character", displayName: "孫悟空", kanaSequence: ["ご","く","う"], speakText: "ごくう", rewardMode: "celebrate", tags: ["角色","入門"] },
  { id: "sakura", contentType: "character", displayName: "さくら", kanaSequence: ["さ","く","ら"], speakText: "さくら", rewardMode: "celebrate", tags: ["角色","入門"] },
  { id: "domain", contentType: "skill", displayName: "領域展開", kanaSequence: ["りょ","う","い","き","て","ん","か","い"], speakText: "りょういきてんかい", castSpeakText: "りょういきてんかい！", castSubtitle: "領域展開", rewardMode: "cast_skill", tags: ["招式","拗音"] },

  // —— 角色名（平假名）——
  { id: "naruto", contentType: "character", displayName: "ナルト", kanaSequence: ["ナ","ル","ト"], speakText: "ナルト", rewardMode: "celebrate", tags: ["角色","片仮名"] },
  { id: "luffy", contentType: "character", displayName: "ルフィ", kanaSequence: ["ル","フィ"], speakText: "ルフィ", rewardMode: "celebrate", tags: ["角色","拗音"] },
  { id: "ichigo", contentType: "character", displayName: "いちご", kanaSequence: ["い","ち","ご"], speakText: "いちご", rewardMode: "celebrate", tags: ["角色"] },
  { id: "tanjiro", contentType: "character", displayName: "たんじろう", kanaSequence: ["た","ん","じ","ろ","う"], speakText: "たんじろう", rewardMode: "celebrate", tags: ["角色"] },
  { id: "nezuko", contentType: "character", displayName: "ねずこ", kanaSequence: ["ね","ず","こ"], speakText: "ねずこ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "vegeta", contentType: "character", displayName: "ベジータ", kanaSequence: ["ベ","ジ","ー","タ"], speakText: "ベジータ", rewardMode: "celebrate", tags: ["角色","長音"] },
  { id: "pikachu", contentType: "character", displayName: "ピカチュウ", kanaSequence: ["ピ","カ","チュ","ウ"], speakText: "ピカチュウ", rewardMode: "celebrate", tags: ["角色","拗音"] },
  { id: "ashitaka", contentType: "character", displayName: "アシタカ", kanaSequence: ["ア","シ","タ","カ"], speakText: "アシタカ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "totoro", contentType: "character", displayName: "トトロ", kanaSequence: ["ト","ト","ロ"], speakText: "トトロ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "chihiro", contentType: "character", displayName: "ちひろ", kanaSequence: ["ち","ひ","ろ"], speakText: "ちひろ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "howl", contentType: "character", displayName: "ハウル", kanaSequence: ["ハ","ウ","ル"], speakText: "ハウル", rewardMode: "celebrate", tags: ["角色"] },
  { id: "eren", contentType: "character", displayName: "エレン", kanaSequence: ["エ","レ","ン"], speakText: "エレン", rewardMode: "celebrate", tags: ["角色"] },
  { id: "mikasa", contentType: "character", displayName: "ミカサ", kanaSequence: ["ミ","カ","サ"], speakText: "ミカサ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "levi", contentType: "character", displayName: "リヴァイ", kanaSequence: ["リ","ヴァ","イ"], speakText: "リヴァイ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "saitama", contentType: "character", displayName: "サイタマ", kanaSequence: ["サ","イ","タ","マ"], speakText: "サイタマ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "genos", contentType: "character", displayName: "ジェノス", kanaSequence: ["ジェ","ノ","ス"], speakText: "ジェノス", rewardMode: "celebrate", tags: ["角色","拗音"] },
  { id: "midoriya", contentType: "character", displayName: "みどりや", kanaSequence: ["み","ど","り","や"], speakText: "みどりや", rewardMode: "celebrate", tags: ["角色"] },
  { id: "bakugo", contentType: "character", displayName: "ばくごう", kanaSequence: ["ば","く","ご","う"], speakText: "ばくごう", rewardMode: "celebrate", tags: ["角色"] },
  { id: "rem", contentType: "character", displayName: "レム", kanaSequence: ["レ","ム"], speakText: "レム", rewardMode: "celebrate", tags: ["角色","入門"] },
  { id: "ram", contentType: "character", displayName: "ラム", kanaSequence: ["ラ","ム"], speakText: "ラム", rewardMode: "celebrate", tags: ["角色","入門"] },
  { id: "asuna", contentType: "character", displayName: "アスナ", kanaSequence: ["ア","ス","ナ"], speakText: "アスナ", rewardMode: "celebrate", tags: ["角色"] },
  { id: "kirito", contentType: "character", displayName: "キリト", kanaSequence: ["キ","リ","ト"], speakText: "キリト", rewardMode: "celebrate", tags: ["角色"] },

  // —— 招式名 ——
  { id: "kamehameha", contentType: "skill", displayName: "かめはめ波", kanaSequence: ["か","め","は","め","は"], speakText: "かめはめは", castSpeakText: "かめはめはー！", castSubtitle: "かめはめ波", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "rasengan", contentType: "skill", displayName: "螺旋丸", kanaSequence: ["ら","せ","ん","が","ん"], speakText: "らせんがん", castSpeakText: "らせんがん！", castSubtitle: "螺旋丸", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "chidori", contentType: "skill", displayName: "千鳥", kanaSequence: ["ち","ど","り"], speakText: "ちどり", castSpeakText: "ちどり！", castSubtitle: "千鳥", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "bankai", contentType: "skill", displayName: "卍解", kanaSequence: ["ば","ん","か","い"], speakText: "ばんかい", castSpeakText: "ばんかい！", castSubtitle: "卍解", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "getsuga", contentType: "skill", displayName: "月牙天衝", kanaSequence: ["げ","つ","が","て","ん","しょ","う"], speakText: "げつがてんしょう", castSpeakText: "げつがてんしょう！", castSubtitle: "月牙天衝", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "finalflash", contentType: "skill", displayName: "ファイナルフラッシュ", kanaSequence: ["ファ","イ","ナ","ル","フ","ラ","ッ","シュ"], speakText: "ファイナルフラッシュ", castSpeakText: "ファイナルフラッシュ！", castSubtitle: "ファイナルフラッシュ", rewardMode: "cast_skill", tags: ["招式","片仮名"] },
  { id: "spiritbomb", contentType: "skill", displayName: "元気玉", kanaSequence: ["げ","ん","き","だ","ま"], speakText: "げんきだま", castSpeakText: "げんきだま！", castSubtitle: "元気玉", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "sharingan", contentType: "skill", displayName: "写輪眼", kanaSequence: ["しゃ","り","ん","が","ん"], speakText: "しゃりんがん", castSpeakText: "しゃりんがん！", castSubtitle: "写輪眼", rewardMode: "cast_skill", tags: ["招式","拗音"] },
  { id: "susanoo", contentType: "skill", displayName: "須佐能乎", kanaSequence: ["す","さ","の","お"], speakText: "すさのお", castSpeakText: "すさのお！", castSubtitle: "須佐能乎", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "amaterasu", contentType: "skill", displayName: "天照", kanaSequence: ["あ","ま","て","ら","す"], speakText: "あまてらす", castSpeakText: "あまてらす！", castSubtitle: "天照", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "hijutsu", contentType: "skill", displayName: "影分身の術", kanaSequence: ["か","げ","ぶ","ん","し","ん","の","じゅ","つ"], speakText: "かげぶんしんのじゅつ", castSpeakText: "かげぶんしんのじゅつ！", castSubtitle: "影分身の術", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "omoiyari", contentType: "skill", displayName: "水の呼吸", kanaSequence: ["み","ず","の","こ","きゅ","う"], speakText: "みずのこきゅう", castSpeakText: "みずのこきゅう！", castSubtitle: "水の呼吸", rewardMode: "cast_skill", tags: ["招式","拗音"] },
  { id: "hinokami", contentType: "skill", displayName: "ヒノカミ神楽", kanaSequence: ["ヒ","ノ","カ","ミ","か","ぐ","ら"], speakText: "ヒノカミかぐら", castSpeakText: "ヒノカミかぐら！", castSubtitle: "ヒノカミ神楽", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "oneforall", contentType: "skill", displayName: "ワン・フォー・オール", kanaSequence: ["ワ","ン","フォ","ー","オ","ー","ル"], speakText: "ワンフォーオール", castSpeakText: "ワンフォーオール！", castSubtitle: "ワン・フォー・オール", rewardMode: "cast_skill", tags: ["招式","片仮名"] },
  { id: "detroit", contentType: "skill", displayName: "デトロイトスマッシュ", kanaSequence: ["デ","ト","ロ","イ","ト","ス","マ","ッ","シュ"], speakText: "デトロイトスマッシュ", castSpeakText: "デトロイトスマッシュ！", castSubtitle: "デトロイトスマッシュ", rewardMode: "cast_skill", tags: ["招式","長詞"] },
  { id: "expulsion", contentType: "skill", displayName: "爆破", kanaSequence: ["ば","く","は"], speakText: "ばくは", castSpeakText: "ばくは！", castSubtitle: "爆破", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "seriouspunch", contentType: "skill", displayName: "マジ殴り", kanaSequence: ["マ","ジ","な","ぐ","り"], speakText: "マジなぐり", castSpeakText: "マジなぐり！", castSubtitle: "マジ殴り", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "gumgum", contentType: "skill", displayName: "ゴムゴムのピストル", kanaSequence: ["ゴ","ム","ゴ","ム","の","ピ","ス","ト","ル"], speakText: "ゴムゴムのピストル", castSpeakText: "ゴムゴムのピストル！", castSubtitle: "ゴムゴムのピストル", rewardMode: "cast_skill", tags: ["招式","長詞"] },
  { id: "gearsecond", contentType: "skill", displayName: "ギア・セカンド", kanaSequence: ["ギ","ア","セ","カ","ン","ド"], speakText: "ギアセカンド", castSpeakText: "ギアセカンド！", castSubtitle: "ギア・セカンド", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "blackflash", contentType: "skill", displayName: "黒閃", kanaSequence: ["こ","く","せ","ん"], speakText: "こくせん", castSpeakText: "こくせん！", castSubtitle: "黒閃", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "hollowpurple", contentType: "skill", displayName: "虚式茈", kanaSequence: ["きょ","し","き","む","ら","さ","き"], speakText: "きょしきむらさき", castSpeakText: "きょしきむらさき！", castSubtitle: "虚式茈", rewardMode: "cast_skill", tags: ["招式","拗音"] },
  { id: "infinitevoid", contentType: "skill", displayName: "無量空処", kanaSequence: ["む","りょ","う","く","う","しょ"], speakText: "むりょうくうしょ", castSpeakText: "むりょうくうしょ！", castSubtitle: "無量空処", rewardMode: "cast_skill", tags: ["招式","拗音"] },
  { id: "malevolent", contentType: "skill", displayName: "伏魔御厨子", kanaSequence: ["ふ","く","ま","ご","ず","し"], speakText: "ふくまごずし", castSpeakText: "ふくまごずし！", castSubtitle: "伏魔御厨子", rewardMode: "cast_skill", tags: ["招式"] },
  { id: "shikai", contentType: "skill", displayName: "始解", kanaSequence: ["し","か","い"], speakText: "しかい", castSpeakText: "しかい！", castSubtitle: "始解", rewardMode: "cast_skill", tags: ["招式","入門"] },
  { id: "hado31", contentType: "skill", displayName: "赤火砲", kanaSequence: ["しゃ","っ","か","ほ","う"], speakText: "しゃっかほう", castSpeakText: "しゃっかほう！", castSubtitle: "赤火砲", rewardMode: "cast_skill", tags: ["招式","拗音"] },

  // —— 自創／中二招式（可練習長詞）——
  { id: "custom_star", contentType: "custom_skill", displayName: "星屑螺旋", kanaSequence: ["ほ","し","く","ず","ら","せ","ん"], speakText: "ほしくずらせん", castSpeakText: "ほしくずらせん！", castSubtitle: "星屑螺旋", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_thunder", contentType: "custom_skill", displayName: "蒼天雷鳴斬", kanaSequence: ["そ","う","て","ん","ら","い","め","い","ざ","ん"], speakText: "そうてんらいめいざん", castSpeakText: "そうてんらいめいざん！", castSubtitle: "蒼天雷鳴斬", rewardMode: "cast_skill", tags: ["自創","長詞"] },
  { id: "custom_moon", contentType: "custom_skill", displayName: "月影一閃", kanaSequence: ["つ","き","か","げ","い","っ","せ","ん"], speakText: "つきかげいっせん", castSpeakText: "つきかげいっせん！", castSubtitle: "月影一閃", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_flame", contentType: "custom_skill", displayName: "紅蓮業火", kanaSequence: ["ぐ","れ","ん","ご","う","か"], speakText: "ぐれんごうか", castSpeakText: "ぐれんごうか！", castSubtitle: "紅蓮業火", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_ice", contentType: "custom_skill", displayName: "絶対零度", kanaSequence: ["ぜ","っ","た","い","れ","い","ど"], speakText: "ぜったいれいど", castSpeakText: "ぜったいれいど！", castSubtitle: "絶対零度", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_wind", contentType: "custom_skill", displayName: "疾風迅雷", kanaSequence: ["し","っ","ぷ","う","じ","ん","ら","い"], speakText: "しっぷうじんらい", castSpeakText: "しっぷうじんらい！", castSubtitle: "疾風迅雷", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_void", contentType: "custom_skill", displayName: "虚空断裂", kanaSequence: ["こ","く","う","だ","ん","れ","つ"], speakText: "こくうだんれつ", castSpeakText: "こくうだんれつ！", castSubtitle: "虚空断裂", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_dragon", contentType: "custom_skill", displayName: "竜神の咆哮", kanaSequence: ["りゅ","う","じ","ん","の","ほ","う","こ","う"], speakText: "りゅうじんのほうこう", castSpeakText: "りゅうじんのほうこう！", castSubtitle: "竜神の咆哮", rewardMode: "cast_skill", tags: ["自創","拗音"] },
  { id: "custom_light", contentType: "custom_skill", displayName: "聖光の審判", kanaSequence: ["せ","い","こ","う","の","し","ん","ぱ","ん"], speakText: "せいこうのしんぱん", castSpeakText: "せいこうのしんぱん！", castSubtitle: "聖光の審判", rewardMode: "cast_skill", tags: ["自創"] },
  { id: "custom_shadow", contentType: "custom_skill", displayName: "闇影縛鎖", kanaSequence: ["あ","ん","え","い","ば","く","さ"], speakText: "あんえいばくさ", castSpeakText: "あんえいばくさ！", castSubtitle: "闇影縛鎖", rewardMode: "cast_skill", tags: ["自創"] },

  // —— 日常・N5 詞彙（celebrate）——
  { id: "arigatou", contentType: "vocab", displayName: "ありがとう", kanaSequence: ["あ","り","が","と","う"], speakText: "ありがとう", rewardMode: "celebrate", tags: ["日常","入門"] },
  { id: "ohayou", contentType: "vocab", displayName: "おはよう", kanaSequence: ["お","は","よ","う"], speakText: "おはよう", rewardMode: "celebrate", tags: ["日常","入門"] },
  { id: "konnichiwa", contentType: "vocab", displayName: "こんにちは", kanaSequence: ["こ","ん","に","ち","は"], speakText: "こんにちは", rewardMode: "celebrate", tags: ["日常","入門"] },
  { id: "konbanwa", contentType: "vocab", displayName: "こんばんは", kanaSequence: ["こ","ん","ば","ん","は"], speakText: "こんばんは", rewardMode: "celebrate", tags: ["日常"] },
  { id: "sayounara", contentType: "vocab", displayName: "さようなら", kanaSequence: ["さ","よ","う","な","ら"], speakText: "さようなら", rewardMode: "celebrate", tags: ["日常"] },
  { id: "sumimasen", contentType: "vocab", displayName: "すみません", kanaSequence: ["す","み","ま","せ","ん"], speakText: "すみません", rewardMode: "celebrate", tags: ["日常"] },
  { id: "gomen", contentType: "vocab", displayName: "ごめん", kanaSequence: ["ご","め","ん"], speakText: "ごめん", rewardMode: "celebrate", tags: ["日常","入門"] },
  { id: "onegaishimasu", contentType: "vocab", displayName: "お願いします", kanaSequence: ["お","ね","が","い","し","ま","す"], speakText: "おねがいします", rewardMode: "celebrate", tags: ["日常"] },
  { id: "douzo", contentType: "vocab", displayName: "どうぞ", kanaSequence: ["ど","う","ぞ"], speakText: "どうぞ", rewardMode: "celebrate", tags: ["日常","入門"] },
  { id: "hai", contentType: "vocab", displayName: "はい", kanaSequence: ["は","い"], speakText: "はい", rewardMode: "celebrate", tags: ["日常","入門"] },
  { id: "iie", contentType: "vocab", displayName: "いいえ", kanaSequence: ["い","い","え"], speakText: "いいえ", rewardMode: "celebrate", tags: ["日常","入門"] },
  { id: "wakarimasu", contentType: "vocab", displayName: "わかります", kanaSequence: ["わ","か","り","ま","す"], speakText: "わかります", rewardMode: "celebrate", tags: ["日常"] },
  { id: "tabemasu", contentType: "vocab", displayName: "たべます", kanaSequence: ["た","べ","ま","す"], speakText: "たべます", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "nomimasu", contentType: "vocab", displayName: "のみます", kanaSequence: ["の","み","ま","す"], speakText: "のみます", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "ikimasu", contentType: "vocab", displayName: "いきます", kanaSequence: ["い","き","ま","す"], speakText: "いきます", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "kimasu", contentType: "vocab", displayName: "きます", kanaSequence: ["き","ま","す"], speakText: "きます", rewardMode: "celebrate", tags: ["動詞","入門"] },
  { id: "mimasu", contentType: "vocab", displayName: "みます", kanaSequence: ["み","ま","す"], speakText: "みます", rewardMode: "celebrate", tags: ["動詞","入門"] },
  { id: "kikimasu", contentType: "vocab", displayName: "ききます", kanaSequence: ["き","き","ま","す"], speakText: "ききます", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "hanashimasu", contentType: "vocab", displayName: "はなします", kanaSequence: ["は","な","し","ま","す"], speakText: "はなします", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "yomimasu", contentType: "vocab", displayName: "よみます", kanaSequence: ["よ","み","ま","す"], speakText: "よみます", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "kakimasu", contentType: "vocab", displayName: "かきます", kanaSequence: ["か","き","ま","す"], speakText: "かきます", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "benkyou", contentType: "vocab", displayName: "べんきょう", kanaSequence: ["べ","ん","きょ","う"], speakText: "べんきょう", rewardMode: "celebrate", tags: ["名詞","拗音"] },
  { id: "gakkou", contentType: "vocab", displayName: "がっこう", kanaSequence: ["が","っ","こ","う"], speakText: "がっこう", rewardMode: "celebrate", tags: ["名詞","促音"] },
  { id: "sensei", contentType: "vocab", displayName: "せんせい", kanaSequence: ["せ","ん","せ","い"], speakText: "せんせい", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "tomodachi", contentType: "vocab", displayName: "ともだち", kanaSequence: ["と","も","だ","ち"], speakText: "ともだち", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "kazoku", contentType: "vocab", displayName: "かぞく", kanaSequence: ["か","ぞ","く"], speakText: "かぞく", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "nihongo", contentType: "vocab", displayName: "にほんご", kanaSequence: ["に","ほ","ん","ご"], speakText: "にほんご", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "eigo", contentType: "vocab", displayName: "えいご", kanaSequence: ["え","い","ご"], speakText: "えいご", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "mizu", contentType: "vocab", displayName: "みず", kanaSequence: ["み","ず"], speakText: "みず", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "gohan", contentType: "vocab", displayName: "ごはん", kanaSequence: ["ご","は","ん"], speakText: "ごはん", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "pan", contentType: "vocab", displayName: "パン", kanaSequence: ["パ","ン"], speakText: "パン", rewardMode: "celebrate", tags: ["名詞","片仮名","入門"] },
  { id: "ramen", contentType: "vocab", displayName: "ラーメン", kanaSequence: ["ラ","ー","メ","ン"], speakText: "ラーメン", rewardMode: "celebrate", tags: ["名詞","片仮名","長音"] },
  { id: "sushi", contentType: "vocab", displayName: "すし", kanaSequence: ["す","し"], speakText: "すし", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "tempura", contentType: "vocab", displayName: "てんぷら", kanaSequence: ["て","ん","ぷ","ら"], speakText: "てんぷら", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "ocha", contentType: "vocab", displayName: "おちゃ", kanaSequence: ["お","ちゃ"], speakText: "おちゃ", rewardMode: "celebrate", tags: ["名詞","拗音","入門"] },
  { id: "koohii", contentType: "vocab", displayName: "コーヒー", kanaSequence: ["コ","ー","ヒ","ー"], speakText: "コーヒー", rewardMode: "celebrate", tags: ["名詞","片仮名","長音"] },
  { id: "denwa", contentType: "vocab", displayName: "でんわ", kanaSequence: ["で","ん","わ"], speakText: "でんわ", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "terebi", contentType: "vocab", displayName: "テレビ", kanaSequence: ["テ","レ","ビ"], speakText: "テレビ", rewardMode: "celebrate", tags: ["名詞","片仮名"] },
  { id: "pasokon", contentType: "vocab", displayName: "パソコン", kanaSequence: ["パ","ソ","コ","ン"], speakText: "パソコン", rewardMode: "celebrate", tags: ["名詞","片仮名"] },
  { id: "keitai", contentType: "vocab", displayName: "けいたい", kanaSequence: ["け","い","た","い"], speakText: "けいたい", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "densha", contentType: "vocab", displayName: "でんしゃ", kanaSequence: ["で","ん","しゃ"], speakText: "でんしゃ", rewardMode: "celebrate", tags: ["名詞","拗音"] },
  { id: "basu", contentType: "vocab", displayName: "バス", kanaSequence: ["バ","ス"], speakText: "バス", rewardMode: "celebrate", tags: ["名詞","片仮名","入門"] },
  { id: "takushii", contentType: "vocab", displayName: "タクシー", kanaSequence: ["タ","ク","シ","ー"], speakText: "タクシー", rewardMode: "celebrate", tags: ["名詞","片仮名","長音"] },
  { id: "hikouki", contentType: "vocab", displayName: "ひこうき", kanaSequence: ["ひ","こ","う","き"], speakText: "ひこうき", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "jikan", contentType: "vocab", displayName: "じかん", kanaSequence: ["じ","か","ん"], speakText: "じかん", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "kyou", contentType: "vocab", displayName: "きょう", kanaSequence: ["きょ","う"], speakText: "きょう", rewardMode: "celebrate", tags: ["名詞","拗音","入門"] },
  { id: "ashita", contentType: "vocab", displayName: "あした", kanaSequence: ["あ","し","た"], speakText: "あした", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "kinou", contentType: "vocab", displayName: "きのう", kanaSequence: ["き","の","う"], speakText: "きのう", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "ima", contentType: "vocab", displayName: "いま", kanaSequence: ["い","ま"], speakText: "いま", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "asa", contentType: "vocab", displayName: "あさ", kanaSequence: ["あ","さ"], speakText: "あさ", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "hiru", contentType: "vocab", displayName: "ひる", kanaSequence: ["ひ","る"], speakText: "ひる", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "yoru", contentType: "vocab", displayName: "よる", kanaSequence: ["よ","る"], speakText: "よる", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "ookii", contentType: "vocab", displayName: "おおきい", kanaSequence: ["お","お","き","い"], speakText: "おおきい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "chiisai", contentType: "vocab", displayName: "ちいさい", kanaSequence: ["ち","い","さ","い"], speakText: "ちいさい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "atarashii", contentType: "vocab", displayName: "あたらしい", kanaSequence: ["あ","た","ら","し","い"], speakText: "あたらしい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "furui", contentType: "vocab", displayName: "ふるい", kanaSequence: ["ふ","る","い"], speakText: "ふるい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "takai", contentType: "vocab", displayName: "たかい", kanaSequence: ["た","か","い"], speakText: "たかい", rewardMode: "celebrate", tags: ["形容詞","入門"] },
  { id: "yasui", contentType: "vocab", displayName: "やすい", kanaSequence: ["や","す","い"], speakText: "やすい", rewardMode: "celebrate", tags: ["形容詞","入門"] },
  { id: "oishii", contentType: "vocab", displayName: "おいしい", kanaSequence: ["お","い","し","い"], speakText: "おいしい", rewardMode: "celebrate", tags: ["形容詞","入門"] },
  { id: "tanoshii", contentType: "vocab", displayName: "たのしい", kanaSequence: ["た","の","し","い"], speakText: "たのしい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "muzukashii", contentType: "vocab", displayName: "むずかしい", kanaSequence: ["む","ず","か","し","い"], speakText: "むずかしい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "yasashii", contentType: "vocab", displayName: "やさしい", kanaSequence: ["や","さ","し","い"], speakText: "やさしい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "kawaii", contentType: "vocab", displayName: "かわいい", kanaSequence: ["か","わ","い","い"], speakText: "かわいい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "sugoi", contentType: "vocab", displayName: "すごい", kanaSequence: ["す","ご","い"], speakText: "すごい", rewardMode: "celebrate", tags: ["形容詞","入門"] },
  { id: "daijoubu", contentType: "vocab", displayName: "だいじょうぶ", kanaSequence: ["だ","い","じょ","う","ぶ"], speakText: "だいじょうぶ", rewardMode: "celebrate", tags: ["日常","拗音"] },
  { id: "genki", contentType: "vocab", displayName: "げんき", kanaSequence: ["げ","ん","き"], speakText: "げんき", rewardMode: "celebrate", tags: ["日常","入門"] },
  { id: "suki", contentType: "vocab", displayName: "すき", kanaSequence: ["す","き"], speakText: "すき", rewardMode: "celebrate", tags: ["日常","入門"] },
  { id: "kirai", contentType: "vocab", displayName: "きらい", kanaSequence: ["き","ら","い"], speakText: "きらい", rewardMode: "celebrate", tags: ["日常"] },
  { id: "tsukareta", contentType: "vocab", displayName: "つかれた", kanaSequence: ["つ","か","れ","た"], speakText: "つかれた", rewardMode: "celebrate", tags: ["日常"] },
  { id: "nemui", contentType: "vocab", displayName: "ねむい", kanaSequence: ["ね","む","い"], speakText: "ねむい", rewardMode: "celebrate", tags: ["形容詞"] },
  { id: "samui", contentType: "vocab", displayName: "さむい", kanaSequence: ["さ","む","い"], speakText: "さむい", rewardMode: "celebrate", tags: ["形容詞","入門"] },
  { id: "atsui", contentType: "vocab", displayName: "あつい", kanaSequence: ["あ","つ","い"], speakText: "あつい", rewardMode: "celebrate", tags: ["形容詞","入門"] },
  { id: "ame", contentType: "vocab", displayName: "あめ", kanaSequence: ["あ","め"], speakText: "あめ", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "yuki", contentType: "vocab", displayName: "ゆき", kanaSequence: ["ゆ","き"], speakText: "ゆき", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "kaze", contentType: "vocab", displayName: "かぜ", kanaSequence: ["か","ぜ"], speakText: "かぜ", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "haru", contentType: "vocab", displayName: "はる", kanaSequence: ["は","る"], speakText: "はる", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "natsu", contentType: "vocab", displayName: "なつ", kanaSequence: ["な","つ"], speakText: "なつ", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "aki", contentType: "vocab", displayName: "あき", kanaSequence: ["あ","き"], speakText: "あき", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "fuyu", contentType: "vocab", displayName: "ふゆ", kanaSequence: ["ふ","ゆ"], speakText: "ふゆ", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "yama", contentType: "vocab", displayName: "やま", kanaSequence: ["や","ま"], speakText: "やま", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "kawa", contentType: "vocab", displayName: "かわ", kanaSequence: ["か","わ"], speakText: "かわ", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "umi", contentType: "vocab", displayName: "うみ", kanaSequence: ["う","み"], speakText: "うみ", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "sora", contentType: "vocab", displayName: "そら", kanaSequence: ["そ","ら"], speakText: "そら", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "hana", contentType: "vocab", displayName: "はな", kanaSequence: ["は","な"], speakText: "はな", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "ki", contentType: "vocab", displayName: "き", kanaSequence: ["き"], speakText: "き", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "neko", contentType: "vocab", displayName: "ねこ", kanaSequence: ["ね","こ"], speakText: "ねこ", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "inu", contentType: "vocab", displayName: "いぬ", kanaSequence: ["い","ぬ"], speakText: "いぬ", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "tori", contentType: "vocab", displayName: "とり", kanaSequence: ["と","り"], speakText: "とり", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "sakana", contentType: "vocab", displayName: "さかな", kanaSequence: ["さ","か","な"], speakText: "さかな", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "ringo", contentType: "vocab", displayName: "りんご", kanaSequence: ["り","ん","ご"], speakText: "りんご", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "mikan", contentType: "vocab", displayName: "みかん", kanaSequence: ["み","か","ん"], speakText: "みかん", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "banana", contentType: "vocab", displayName: "バナナ", kanaSequence: ["バ","ナ","ナ"], speakText: "バナナ", rewardMode: "celebrate", tags: ["名詞","片仮名","入門"] },
  { id: "aisukuriimu", contentType: "vocab", displayName: "アイスクリーム", kanaSequence: ["ア","イ","ス","ク","リ","ー","ム"], speakText: "アイスクリーム", rewardMode: "celebrate", tags: ["名詞","片仮名","長音"] },
  { id: "chokoreeto", contentType: "vocab", displayName: "チョコレート", kanaSequence: ["チョ","コ","レ","ー","ト"], speakText: "チョコレート", rewardMode: "celebrate", tags: ["名詞","片仮名","拗音"] },
  { id: "keeki", contentType: "vocab", displayName: "ケーキ", kanaSequence: ["ケ","ー","キ"], speakText: "ケーキ", rewardMode: "celebrate", tags: ["名詞","片仮名","長音"] },
  { id: "pizza", contentType: "vocab", displayName: "ピザ", kanaSequence: ["ピ","ザ"], speakText: "ピザ", rewardMode: "celebrate", tags: ["名詞","片仮名","入門"] },
  { id: "hanbaagaa", contentType: "vocab", displayName: "ハンバーガー", kanaSequence: ["ハ","ン","バ","ー","ガ","ー"], speakText: "ハンバーガー", rewardMode: "celebrate", tags: ["名詞","片仮名"] },
  { id: "sandoicchi", contentType: "vocab", displayName: "サンドイッチ", kanaSequence: ["サ","ン","ド","イ","ッ","チ"], speakText: "サンドイッチ", rewardMode: "celebrate", tags: ["名詞","片仮名"] },
  { id: "jutsu", contentType: "vocab", displayName: "じゅつ", kanaSequence: ["じゅ","つ"], speakText: "じゅつ", rewardMode: "celebrate", tags: ["名詞","拗音","入門"] },
  { id: "mahou", contentType: "vocab", displayName: "まほう", kanaSequence: ["ま","ほ","う"], speakText: "まほう", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "ken", contentType: "vocab", displayName: "けん", kanaSequence: ["け","ん"], speakText: "けん", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "tate", contentType: "vocab", displayName: "たて", kanaSequence: ["た","て"], speakText: "たて", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "yoroi", contentType: "vocab", displayName: "よろい", kanaSequence: ["よ","ろ","い"], speakText: "よろい", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "yumi", contentType: "vocab", displayName: "ゆみ", kanaSequence: ["ゆ","み"], speakText: "ゆみ", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "ya", contentType: "vocab", displayName: "や", kanaSequence: ["や"], speakText: "や", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "tatakau", contentType: "vocab", displayName: "たたかう", kanaSequence: ["た","た","か","う"], speakText: "たたかう", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "mamoru", contentType: "vocab", displayName: "まもる", kanaSequence: ["ま","も","る"], speakText: "まもる", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "nigeru", contentType: "vocab", displayName: "にげる", kanaSequence: ["に","げ","る"], speakText: "にげる", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "katsu", contentType: "vocab", displayName: "かつ", kanaSequence: ["か","つ"], speakText: "かつ", rewardMode: "celebrate", tags: ["動詞","入門"] },
  { id: "makeru", contentType: "vocab", displayName: "まける", kanaSequence: ["ま","け","る"], speakText: "まける", rewardMode: "celebrate", tags: ["動詞"] },
  { id: "yuuki", contentType: "vocab", displayName: "ゆうき", kanaSequence: ["ゆ","う","き"], speakText: "ゆうき", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "kibou", contentType: "vocab", displayName: "きぼう", kanaSequence: ["き","ぼ","う"], speakText: "きぼう", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "yume", contentType: "vocab", displayName: "ゆめ", kanaSequence: ["ゆ","め"], speakText: "ゆめ", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "ai", contentType: "vocab", displayName: "あい", kanaSequence: ["あ","い"], speakText: "あい", rewardMode: "celebrate", tags: ["名詞","入門"] },
  { id: "heiwa", contentType: "vocab", displayName: "へいわ", kanaSequence: ["へ","い","わ"], speakText: "へいわ", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "sensou", contentType: "vocab", displayName: "せんそう", kanaSequence: ["せ","ん","そ","う"], speakText: "せんそう", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "shouri", contentType: "vocab", displayName: "しょうり", kanaSequence: ["しょ","う","り"], speakText: "しょうり", rewardMode: "celebrate", tags: ["名詞","拗音"] },
  { id: "haiboku", contentType: "vocab", displayName: "はいぼく", kanaSequence: ["は","い","ぼ","く"], speakText: "はいぼく", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "chikara", contentType: "vocab", displayName: "ちから", kanaSequence: ["ち","か","ら"], speakText: "ちから", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "inochi", contentType: "vocab", displayName: "いのち", kanaSequence: ["い","の","ち"], speakText: "いのち", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "kokoro", contentType: "vocab", displayName: "こころ", kanaSequence: ["こ","こ","ろ"], speakText: "こころ", rewardMode: "celebrate", tags: ["名詞"] },
  { id: "tamashii", contentType: "vocab", displayName: "たましい", kanaSequence: ["た","ま","し","い"], speakText: "たましい", rewardMode: "celebrate", tags: ["名詞"] },
];

// 格數硬上限 16
window.KANA_QUESTIONS = window.KANA_QUESTIONS.map((q) => {
  if (q.kanaSequence.length > 16) {
    console.warn("[題庫] 超過 16 格已截斷:", q.id);
    q.kanaSequence = q.kanaSequence.slice(0, 16);
  }
  return q;
});
